### ISSUE TITLE
[BUG] MongoParseError: Unsupported Option 'useFindAndModify' in Connection String

### ISSUE THREAD

**Issue by anothercoder-nik** [kartikayasijaa/talk-trove#112]
**Describe the bug**
When starting the Node.js server using server.js, an error occurs due to the unsupported option useFindAndModify in the MongoDB connection string, resulting in a MongoParseError. This error prevents the application from connecting to the MongoDB database and causes the server to crash. To resolve this issue, the connection options in db.js should be reviewed to remove or replace the useFindAndModify option with supported alternatives, and it may also be necessary to update the Mongoose version to ensure compatibility with the latest MongoDB driver.

**To Reproduce**
1. Go to 'talk-trove'
2. Click on 'talk-trove/backend'
3. Start Serve  ' yarn run dev'
4. See error - 
Server running on PORT 5000...
C:\Users\codeb\Downloads\project\talk-trove\backend\node_modules\mongodb\lib\connection_string.js:272
        throw new error_1.MongoParseError(${optionWord} ${Array.from(unsupportedOptions).join(', ')} ${isOrAre} not supported);
              ^

MongoParseError: option usefindandmodify is not supported
    at parseOptions (C:\Users\codeb\Downloads\project\talk-trove\backend\node_modules\mongodb\lib\connection_string.js:272:15)    at new MongoClient (C:\Users\codeb\Downloads\project\talk-trove\backend\node_modules\mongodb\lib\mongo_client.js:52:63)   
    at NativeConnection.createClient (C:\Users\codeb\Downloads\project\talk-trove\backend\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:312:14)
    at NativeConnection.openUri (C:\Users\codeb\Downloads\project\talk-trove\backend\node_modules\mongoose\lib\connection.js:835:34)
    at Mongoose.connect (C:\Users\codeb\Downloads\project\talk-trove\backend\node_modules\mongoose\lib\mongoose.js:447:15)    
    at connectDB (C:\Users\codeb\Downloads\project\talk-trove\backend\config\db.js:6:33)
    at Object.<anonymous> (C:\Users\codeb\Downloads\project\talk-trove\backend\server.js:12:1)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  [Symbol(errorLabels)]: Set(0) {}
}
Node.js v18.20.4
[nodemon] app crashed - waiting for file changes before starting...

**Expected behavior**
The expected behavior is for the Node.js server to start successfully and establish a connection to the MongoDB database without encountering any errors. Upon successful connection, the server should log a message indicating that it is running on the specified port (e.g., "Server running on PORT 5000...") and be ready to handle incoming requests. Removing or replacing the unsupported useFindAndModify option in the MongoDB connection string should allow the application to function as intended, enabling seamless interaction with the database and ensuring that the server remains stable and responsive.

**Screenshots**
![issue2_1](https://github.com/user-attachments/assets/6e157b49-959c-4a3c-9988-6a592be48e7b)
![issue2_2](https://github.com/user-attachments/assets/28d53bcb-3075-43ff-85fd-e8fd949260a3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Edge
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: Motorola G54 5G
 - OS: Android 14
 - Browser: Chrome
 - Version: Latest

**Additional context**
The useFindAndModify option was deprecated in Mongoose 5.x and later versions due to changes in the MongoDB driver. This deprecation may lead to compatibility issues when using recent versions of the MongoDB Node.js driver, as certain options are no longer supported. This bug was encountered during the development phase while attempting to establish a database connection, which is a critical step for the application to function correctly. The application aims to provide a robust backend service, and resolving this issue is essential for maintaining stability and ensuring that all database-related operations can be performed without interruption.

This fix is particularly important for developers working on the project, as it will prevent future issues related to outdated configuration options and facilitate a smoother development process. Additionally, addressing this bug will enhance the overall user experience by ensuring that the application runs reliably and efficiently.

- Gssoc'24 - Extender Contributor
- HacktoberFest'24 Contributor

**Comment by Sibam-Paul** [comment]
@anothercoder-nik  test branch is active not the main

**Comment by Sibam-Paul** [comment]
u have skipped the command "yarn" before yarn run dev

**Comment by Sibam-Paul** [comment]
Raise question in discussion if u have further problem @anothercoder-nik

**Comment by Sibam-Paul** [comment]
#115 go here
